### ISSUE TITLE
the debugging level in chapter3 

### ISSUE THREAD

**Issue by StanleyYake** [AaronMR/Learning_ROS_for_Robotics_Programming#1]
Hello AaronMr,I followed your guide in the charpter 3 in Learning ROS for Robotics Programming.Exactly,the example1.cpp,and the snippet 

```
my_logger->setLevel( ros::console::g_level_lookup[ros::console::levels::Debug]  );
```

can't build successfully,my IDE told me the g_level_lookup is not a member of ros::console,the member of ros::console is g_formatter,g_initializer,g_last_error_message,Level,TokenPtr and V_Token.I'm new here and I'm using hydro,can you give me some tips?Waiting for your reply:)

**Comment by efernandez** [comment]
Hi,

The book is for fuerte. We'll give support for hydro soon. Indeed, I think
there's a hydro/catkin branch (hydro-devel) for that specific package.

Best,
Enrique

2014-06-09 16:33 GMT+02:00 StanleyYake notifications@github.com:

**Comment by efernandez** [comment]
@StanleyYake Do you still need this? We've already fix it in a separate repo, but I can backport it here.

**Comment by makquel** [comment]
Hi,

I'm experiencing some problems regarding chapter 3 code. First, I solved the problem stated before, adding the headers for log4cxx, i.e. #include <log4cxx/logger.h>, however, later on I had another problem, this is a copy of error log:
/home/xxx/dev/rosbook/chapter3_tutorials/src/example1.cpp:17:23: error: ‘g_level_lookup’ is not a member of ‘ros::console’
     my_logger->setLevel(ros::console::g_level_lookup[ros::console::levels::Debug]);
Could you send me the link of newest repo? BTW, I'm using indigo version of ROS

**Comment by efernandez** [comment]
@makquel The API changed in ROS indigo, and this code was for ROS fuerte.
By next year we'll probably publish something for ROS hydro... we're working on it. If you send me an e-mail I can give you the instructions to do this in ROS hydro (which should work in ROS indigo as well).

**Comment by makquel** [comment]
@efernandez It's done.

**Comment by efernandez** [comment]
For versions newer than ROS fuerte you need:
- Add this header:

``` c++
#include <ros/console.h>
```
- Change the following block into this one:

``` c++
#if OVERRIDE_NODE_VERBOSITY_LEVEL
  // Se the logging level manually to DEBUG
  ros::console::set_logger_level(ROSCONSOLE_DEFAULT_NAME, ros::console::levels::Debug);
#endif
```

Closing the issue...
