### ISSUE TITLE
Missing urdf.vcg file in chapter5_tutorials

### ISSUE THREAD

**Issue by tyuownu** [AaronMR/Learning_ROS_for_Robotics_Programming#5]
Hi AaronMR
    When I run the example code in chapter 5. I found an ERROR.  In the chapter5_tutorials folder donot have the urdf.vcg file. BUT in the launch/state_xacro.launch, line 8 <node name="rviz" pkg="rviz" type="rviz" args="-d $(find chapter5_tutorials)/urdf.vcg" />. The urdf.vcg does not belong to chapter5_tutorials, but belongs to urdf_tutorial. PLZ cheak it out.
    thank you!

**Comment by efernandez** [comment]
@AaronMR do you have the vcg file? If not, we can re-generate it easily from rviz

**Comment by tyuownu** [comment]
Use the urdf.vcg file from urdf_tutorial package, everything goes fine.
