### ISSUE TITLE
SetSpeed.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [AaronMR/Learning_ROS_for_Robotics_Programming#6]
I have got this error how can I solve.
Building CXX object CMakeFiles/example4.dir/src/example4.cpp.o
  /home/ubuntutux/dev/rosbook/chapter3_tutorials/src/example4.cpp:7:41: fatal error: chapter3_tutorials/SetSpeed.h: No such file or directory
   #include <chapter3_tutorials/SetSpeed.h>
                                           ^
  compilation terminated.

**Comment by efernandez** [comment]
Simply run compilation again for now.

The problem is that example4 needs the autogenerated headers for SetSpeed service.
In the CMakeLists.txt it needs a dependency.

**Comment by RahulKode** [comment]
what dependency is needed in CMakeLists.txt ?
